<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
     $menu = array('menu' => 'admin_top_menu');
     echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [Courier Company List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s company found.', $count);
        }else{
            echo $this->translate('Total %s companies found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Delete Selected'); ?>
              </a>
              <a href="<?php echo $this->url(array('action' => 'export'), 'admin_courier_general', true); ?>" class="btn">
                  <i class="icon-download-alt"></i>
                  <?php echo $this->translate('Export Couriers'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="checkall" id="checkallitems" value="all" />
                </th>
                <th><?php echo $this->translate('Company Details'); ?></th>
                <th style="width: 225px;"><?php echo $this->translate('Company Address'); ?></th>
                <th style="width: 180px;"><?php echo $this->translate('Location Details'); ?></th>
                <th style="width: 150px;"><?php echo $this->translate('Location (Lat/Lng)'); ?></th>
                <th style="width: 50px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <?php
                        echo "<a href='{$item->getHref()}'>{$item->getTitle()}</a><br />";
                        echo $this->translate('Contact Name: %s', $item->getContactName()) ."<br />";
                        echo $this->translate('Mobile Number: %s', $item->getMobileNo())."<br />";
                        echo $this->translate('Phone Number: %s', $item->getPhoneNo())."<br />";
                        echo $this->translate('Email: %s', "<a href='mailto:{$item->getEmail()}'>{$item->getEmail()}</a>")."<br />";
                        echo $this->translate('Website: %s', "<a href='{$item->getWebsite()}' target='_blank'>{$item->getWebsite()}</a>");
                        ?>
                    </td>                
                    <td><?php echo $item->getAddress(); ?></td>
                    <td>
                        <?php 
                            echo "{$this->translate('City / Town: %s', $item->getCity()->getTitle())}<br />"; 
                            echo "{$this->translate('County: %s', $item->getCounty()->getTitle())}<br />"; 
                            echo "{$this->translate('Post Code: %s', $item->getPostCode())}<br />"; 
                            echo "{$this->translate('Country: %s', $item->getCountry()->getTitle())}"; 
                        ?>
                    </td>
                    <td>
                        <?php 
                            echo "{$this->translate('Lat: %s', $item->getLatitude())}<br />"; 
                            echo "{$this->translate('Lng: %s', $item->getLongitude())}<br />";
                            echo "{$this->translate('IP: %s', $item->getIpAddress())}<br />";
                            echo "{$this->translate('Created: %s', @date('Y-m-d', strtotime($item->getCreationDate())))}\n"; 
                            echo "{$this->translate('Modified: %s', @date('Y-m-d', strtotime($item->getModifiedDate())))}\n"; 
                        ?>
                    </td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-vertical">
                              <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getIdentity()), 'admin_courier_action', true); ?>" class="btn" title="<?php echo $this->translate('Edit'); ?>">
                                  <i class="icon-edit"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Delete'); ?>">
                                  <i class="icon-trash"></i>
                              </a>
                              <a href="javascript:void(0)" class="btn dropdown-toggle" style="border-radius: 0px 0px 4px 4px;" data-toggle="dropdown" title="<?php echo $this->translate('Action List'); ?>">
                                  <i class="icon-list"></i>
                              </a>
                              <ul class="dropdown-menu pull-right custsubnav">
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'vehicles', 'id' => $item->getIdentity()), 'admin_courier_action', true); ?>">
                                         <i class="icon-road"></i>
                                         <?php echo $this->translate('Vehicles Info'); ?>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'insurance', 'id' => $item->getIdentity()), 'admin_courier_action', true); ?>">
                                         <i class="icon-lock"></i>
                                         <?php echo $this->translate('Insurance Info'); ?>
                                     </a>
                                 </li>                                 
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'payment-terms', 'id' => $item->getIdentity()), 'admin_courier_action', true); ?>">
                                         <i class="icon-briefcase"></i>
                                         <?php echo $this->translate('Payment Terms'); ?>
                                     </a>
                                 </li>                                 
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'services', 'id' => $item->getIdentity()), 'admin_courier_action', true); ?>">
                                         <i class="icon-wrench"></i>
                                         <?php echo $this->translate('Services Info'); ?>
                                     </a>
                                 </li>                                 
                              </ul>                               
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected companies?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_courier_general', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any company!'); ?>');
        }
    }
});
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the company?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_courier_general', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}

$('#country').change(function(){
    if($(this).val() == ''){return false;}
    var $countyRequest = $.ajax({
        url: "<?php echo $this->url(array('controller' => 'ajax', 'action' => 'get-county-list'), 'default', true); ?>",
        type: "GET",
        data: {country: $(this).val()},
        dataType: "json"
    });
    $countyRequest.done(function($result) {
        if($result.status == 'success'){
            var $countyOptions = "<option label='' value=''></option>";
            $.each($result.result, function($key, $value){
                $countyOptions += "<option label='"+$value+"' value='"+$key+"'>"+$value+"</option>";
            });

            $('#county').html($countyOptions);
        }else{
            alert("<?php echo $this->translate('Sorry, unable to get county list!'); ?>");
        }
    });
    $countyRequest.fail(function(jqXHR, textStatus) {
        alert("<?php echo $this->translate('Request failed: '); ?>" + textStatus);
    });    
});
$('#county').change(function(){
    if($(this).val() == ''){return false;}
    var $townRequest = $.ajax({
        url: "<?php echo $this->url(array('controller' => 'ajax', 'action' => 'get-town-list'), 'default', true); ?>",
        type: "GET",
        data: {county: $(this).val()},
        dataType: "json"
    });
    $townRequest.done(function($result) {
        if($result.status == 'success'){
            var $townOptions = "<option label='' value=''></option>";
            $.each($result.result, function($key, $value){
                $townOptions += "<option label='"+$value+"' value='"+$key+"'>"+$value+"</option>";
            });

            $('#city').html($townOptions);
        }else{
            alert("<?php echo $this->translate('Sorry, unable to get city/town list!'); ?>");
        }
    });
    $townRequest.fail(function(jqXHR, textStatus) {
        alert("<?php echo $this->translate('Request failed: '); ?>" + textStatus);
    });    
});
</script>