<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */

$company = $this->company;
?>

<?php 
    $menu = array('menu' => 'top_menu');
    echo $this->topMenuWidget(array('headtitle' => 'Send Email', 'menu' => $menu)); 
?>

<div id="formholder">
    <h4>
        <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
        <?php echo $this->translate('Send an Email [%s]', $company->getTitle()); ?>
    </h4>

    <div style="clear: both;"><br /></div>

    <div class="span send-email-form" style="margin-left: 0px;">
        <?php if($this->message){ ?>
            <div id="contactsuccess"><?php echo $this->translate($this->message); ?></div>
        <?php } ?>
        <?php echo $this->form->render($this); ?>
    </div>
    <div style="clear: both;"></div>
</div>
    
<script type="text/javascript">
    $('#submit').prepend("<i class='icon-edit icon-white'></i> ");
</script>