<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<?php
$apiKey = (string) $this->apiKey; 
$fileFullPath = $this->fileFullPath;

// auto google map js
$this->headScript()
        ->appendFile("http://maps.google.com/maps/api/js?key={$apiKey}")
        ->appendFile("public/externals/cluster-mapping/markerclusterer.js")
        ->appendFile("public/externals/cluster-mapping/downloadxml.js");
        //->appendFile("http://google-maps-utility-library-v3.googlecode.com/svn/trunk/markerclusterer/src/markerclusterer.js")
        //->appendFile("http://www.geocodezip.com/scripts/downloadxml.js");
?>

<script type="text/javascript"> 
    //<![CDATA[
    // this variable will collect the html which will eventually be placed in the side_bar 
    var side_bar_html = ""; 

    // arrays to hold copies of the markers and html used by the side_bar 
    // because the function closure trick doesnt work there 
    var gmarkers = []; 

    // global "map" variable
    var map = null;
    var markerclusterer = null;
    var $baseUrl = "<?php echo $this->baseUrl(); ?>";

    // A function to create the marker and set up the event window function 
    function createMarker(latlng, html){
        var contentString = html;
        var marker = new google.maps.Marker({
            position: latlng,
            // map: map,
            zIndex: Math.round(latlng.lat()*-100000)<<5
        });

        google.maps.event.addListener(marker, 'click', function(){
            infowindow.setContent(contentString); 
            infowindow.open(map, marker);
        });

        // save the info we need to use later for the side_bar
        gmarkers.push(marker);

        // add a line to the side_bar html
        //side_bar_html += '<a href="javascript:myclick(' + (gmarkers.length-1) + ')">' + name + '<\/a><br>';
    }

    // This function picks up the click and opens the corresponding info window
    function myclick(i){
        google.maps.event.trigger(gmarkers[i], "click");
    }

    function initialize(){
        // create the map
        var myOptions = {
            zoom: 11,
            center: new google.maps.LatLng(53.482516, -2.341233),
            //center: new google.maps.LatLng(54.737308, -2.596436),
            mapTypeControl: true,
            mapTypeControlOptions: {style: google.maps.MapTypeControlStyle.DROPDOWN_MENU},
            navigationControl: true,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }

        map = new google.maps.Map(
            document.getElementById("map_canvas"),
            myOptions
        );

        google.maps.event.addListener(map, 'click', function(){
            infowindow.close();
        });

        // Read the data from example.xml
        downloadUrl("gmap-icons/couriers.xml", function(doc){
            var xmlDoc = xmlParse(doc);
            var markers = xmlDoc.documentElement.getElementsByTagName("marker");
            for(var i = 0; i < markers.length; i++){
                // obtain the attribues of each marker
                var $lat = parseFloat(markers[i].getAttribute("lat"));
                var $lng = parseFloat(markers[i].getAttribute("lng"));
                var $point = new google.maps.LatLng($lat, $lng);
                var $county = markers[i].getAttribute("county");
                var $href = markers[i].getAttribute("href");
                var $title = markers[i].getAttribute("title");
                var $email = markers[i].getAttribute("email");
                var $emailhref = markers[i].getAttribute("emailhref");
                var $website = markers[i].getAttribute("website");
                var $mobile = markers[i].getAttribute("mobile");
                var $address = markers[i].getAttribute("address");
                
                // prepare info html
                var $html = "<h3>"+
                                        "<a href='"+$href+"' style='color: #000; font-size: 18px;'>"+
                                            "<i class='icon-shopping-cart' style='vertical-align:middle; margin-top: -2px;'></i>"+
                                            $title +
                                        "</a>"+
                                    "</h3>"+
                                    "<p>"+$mobile+"</p>"+
                                    "<p>"+$address+"</p>"+
                                    "<ul class='comnav'>";

                if($emailhref != null){
                    $html += "<li><a href='"+$baseUrl+$emailhref+"' target='_blank'><?php echo $this->translate('Email Us'); ?></a></li>";
                }if($website != ''){
                    $html += "<li class='seperator'>|</li>"+
                    "<li><a href='"+$website+"' target='_blank'><?php echo $this->translate('Visit Website'); ?></a></li>";
                }
                $html += "<li class='seperator'>|</li>"+
                                "<li><a href='"+$baseUrl+$href+"' target='_blank'><?php echo $this->translate('Full Profile'); ?></a></li>"+
                                "<div style='clear: both;'></div>"+
                            "</ul>";
                
                // create the marker
                var marker = createMarker($point, $html);
            }

            markerCluster = new MarkerClusterer(map, gmarkers);
            // put the assembled side_bar_html contents into the side_bar div
            //document.getElementById("side_bar").innerHTML = side_bar_html;
        });
    }

    var infowindow = new google.maps.InfoWindow({ 
        size: new google.maps.Size(150, 50)
    });
    
    // call initialize
    google.maps.event.addDomListener(window, 'load', initialize);    
    //]]>
</script>

<div id="map_canvas" style="width: 100%; height: 750px;"></div>