<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<?php
$location = $this->location;
$address = $this->address;

// auto google map css
$this->headLink()
        ->appendStylesheet("https://developers.google.com/maps/documentation/javascript/examples/default.css", 'screen', true, array('charset' => "utf-8"));

// auto google map js
$this->headScript()
        ->appendFile("https://maps.googleapis.com/maps/api/js?key=API_KEY");
?>

<script type="text/javascript">
    function initialize() {
        var mapOptions = {
            zoom: 10,
            center: new google.maps.LatLng(-34.028249, 151.157507),
            //center: new google.maps.LatLng(<?php //echo $location->lat; ?>, <?php //echo $location->lng; ?>),
            mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(
            document.getElementById('map-canvas'),
            mapOptions
        );

        setMarkers(map, beaches);
    }

    /**
     * Data for the markers consisting of a name, a LatLng and a zIndex for
     * the order in which these markers should display on top of each
     * other.
     */
    var beaches = [
        ['Bondi Beach', -33.890542, 151.274856, 4],
        //['PDN Office', <?php //echo $location->lat; ?>, <?php //echo $location->lng; ?>, 1]
        ['Cronulla Beach', -34.028249, 151.157507, 3],
        ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
        ['Maroubra Beach', -33.950198, 151.259302, 1]
    ];

    function setMarkers(map, locations) {
        // Add markers to the map

        // Marker sizes are expressed as a Size of X,Y
        // where the origin of the image (0,0) is located
        // in the top left of the image.

        // Origins, anchor positions and coordinates of the marker
        // increase in the X direction to the right and in
        // the Y direction down.
        var image = {
            url: 'public/gmap-icons/point-image.png',
            // This marker is 20 pixels wide by 32 pixels tall.
            size: new google.maps.Size(48, 78),
            // The origin for this image is 0,0.
            origin: new google.maps.Point(0, 0),
            // The anchor for this image is the base of the flagpole at 0,32.
            anchor: new google.maps.Point(24, 78)
        };
        var shadow = {
            url: 'public/gmap-icons/point-shadow.png',
            // The shadow image is larger in the horizontal dimension
            // while the position and offset are the same as for the main image.
            size: new google.maps.Size(76, 79),
            origin: new google.maps.Point(0, 0),
            anchor: new google.maps.Point(24, 79)
        };
                
        // Shapes define the clickable region of the icon.
        // The type defines an HTML &lt;area&gt; element 'poly' which
        // traces out a polygon as a series of X,Y points. The final
        // coordinate closes the poly by connecting to the first
        // coordinate.
        var shape = {
            coord: [1, 1, 1, 79, 76, 79, 76 , 1],
            type: 'poly'
        };
                
        var markers = [];
        var infowindows = [];
        for (var i = 0; i < locations.length; i++) {
            var beach = locations[i];
            var myLatLng = new google.maps.LatLng(beach[1], beach[2]);
                    
            var contentString = '<div><h2><img src="public/gmap-icons/logo.png" style="border: 1px solid #eee; margin-right: 10px;">' + 
                                            '<?php echo $this->translate('Our Office:'); ?></h2>' +
                                            '<div><?php echo $address; ?></div></div>';
            infowindows[i] = new google.maps.InfoWindow({
                content: contentString
            });
                    
            markers[i] = new google.maps.Marker({
                position: myLatLng,
                map: map,
                shadow: shadow,
                icon: image,
                shape: shape,
                title: beach[0],
                zIndex: beach[3]
            });
            
            // load infowindow on load
            //infowindow.open(map, marker);
            
            // load infowindow on click
            google.maps.event.addListener(markers[i], 'click', function() {
                infowindows[i].open(map, markers[i]);
            });                    
        }
    }

    google.maps.event.addDomListener(window, 'load', initialize);
</script>

<div id="map-canvas" style="width: 100%; height: 550px;"></div>
<div style="clear: both;"></div>