<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<?php echo $this->filterForm->render($this); ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
</script>