<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<div class="hero-unit" style="padding: 135px 60px; margin-bottom: 0px;">
    <h1 style="text-align: center;">
        Welcome 
        <br />
        to 
        <br />
        Courier Database Search!
    </h1>
</div>