<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */

$company = $this->company;
?>

<style type="text/css">
    dd {float: left; margin-right: 10px;}
    dd > input[type="checkbox"] {margin-top: 0px;}
    dt {display: block;}
</style>

<?php
$menu = array('menu' => 'admin_top_menu');
echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<div id="formholder">
    <h4>
        <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
        <?php echo $this->translate('Admin Panel [Edit Service of %s]', $company->getTitle()); ?>
    </h4>

    <div style="clear: both;"><br /></div>

    <div class="span add-company-form" style="margin-left: 0px;">
        <?php echo $this->form->render($this); ?>
    </div>
    <div style="clear: both;"></div>
</div>

<script type="text/javascript">
$('#dummy1').html("<i class='icon-info-sign'></i> <?php echo $this->translate('Tick all services that apply.'); ?>");
//$('#dummy2').html('<?php //echo $this->translate('You can add or amend these details later.'); ?>');
$('#submit').prepend("<i class='icon-edit icon-white'></i> ");
</script>