<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
     $menu = array('menu' => 'admin_top_menu');
     echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [Mail List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s mail found.', $count);
        }else{
            echo $this->translate('Total %s mails found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="<?php echo $this->url(array('action' => 'add'), 'admin_mail_general', true); ?>" class="btn">
                  <i class="icon-edit"></i>
                  <?php echo $this->translate('Compose New Mail'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Delete Selected'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
      </div>
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="checkall" id="checkallitems" value="all" />
                </th>
                <th style="width: 190px;"><?php echo $this->translate('Mail Subject'); ?></th>
                <th><?php echo $this->translate('Mail Body'); ?></th>
                <th style="width: 120px;"><?php echo $this->translate('Mail Status'); ?></th>
                <th style="width: 135px;"><?php echo $this->translate('Date & Time'); ?></th>
                <th style="width: 50px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td><?php echo $item->getSubject(); ?></td>
                    <td><?php echo strip_tags(html_entity_decode($item->getBody())); ?></td>
                    <td>
                        <?php 
                            if($item->isEnabled()){
                                echo $this->translate('Mail: Enabled');
                            }else{
                                echo $this->translate('Mail: Disabled');
                            }
                            echo "<br />";
                            echo $this->translate('Mail Sent: %s', Zend_Locale_Format::toNumber($item->getSent()));
                            echo "<br />";
                            echo $this->translate('Status: %s', $item->getStatus());
                        ?>
                    </td>
                    <td>
                        <?php echo $this->translate('Creation Date:%1$s %2$s', '<br />', $item->getCreationDate()); ?>
                        <br /><br />
                        <?php echo $this->translate('Modified Date:%1$s %2$s', '<br />', $item->getModifiedDate()); ?>
                    </td>
                    <td style="text-align: center;">
                        <div id="loaderPan<?php echo $item->getIdentity(); ?>"></div>
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-vertical">
                              <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getIdentity()), 'admin_mail_action', true); ?>" class="btn" title="<?php echo $this->translate('Edit'); ?>">
                                  <i class="icon-edit"></i>
                              </a>
                              <?php
                              if(!$item->isEnabled()){
                                  $keyText = 'enable';
                                  $titleText = $this->translate('Enable');
                              }else{
                                  $keyText = 'disable';
                                  $titleText = $this->translate('Disable');
                              }
                              ?>
                              <a href="javascript:void(0)" onclick="javascript:changeMailStatus(<?php echo $item->getIdentity(); ?>, '<?php echo $keyText; ?>')" class="btn" title="<?php echo $titleText; ?>">
                                  <?php if(!$item->isEnabled()){ ?>
                                  <i class="icon-ok-circle"></i>
                                  <?php }else{ ?>
                                  <i class="icon-ban-circle"></i>
                                  <?php } ?>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:sendTestMail(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Test Mail'); ?>">
                                  <i class="icon-envelope"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:resetThisMail(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Reset Mail'); ?>">
                                  <i class="icon-refresh"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Delete'); ?>">
                                  <i class="icon-trash"></i>
                              </a>
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected mails?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_mail_general', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any mail!'); ?>');
        }
    }
});
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the mail?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_mail_general', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function changeMailStatus($itemId, $status){
    var $confirmText = "<?php echo $this->translate('Are you sure to enable the mail?'); ?>";
    if($status == 'disable'){
        $confirmText = "<?php echo $this->translate('Are you sure to disable the mail?'); ?>";
    }
    
    if(confirm($confirmText)){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'status'), 'admin_mail_general', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function resetThisMail($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to reset the mail?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'reset'), 'admin_mail_general', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function sendTestMail($itemId){
    var $request = $.ajax({
        url: "<?php echo $this->url(array('action' => 'test-mail'), 'admin_mail_general', true); ?>/id/"+$itemId,
        type: "GET",
        data: {},
        dataType: "json",
        beforeSend: function(jqXHR){
            $('#loaderPan'+$itemId).html('<img src="public/themes/default/img/loading.gif" />');
        }
    });
    $request.done(function($result){
        if($result.status == 'success'){
            $('#loaderPan'+$itemId).html('<img src="public/themes/default/img/tick.png" />');
            $('#loaderPan'+$itemId).fadeOut(5000);
        }else{            
            $('#loaderPan'+$itemId).html('');
            alert("<?php echo $this->translate('Sorry, something went wrong!'); ?>");
        }
    });
    $request.fail(function(jqXHR, textStatus){
        $('#loaderPan'+$itemId).html('');
        alert("<?php echo $this->translate('Request failed: '); ?>" + textStatus);
    });            
}
</script>