<?php
/**
 * Search Engine for Finding Courier Services
 *
 * @category   Application_Core
 * @package    courier-search-engine
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    courier-search-engine
 */

// auto suggest js
$this->headScript()
          ->appendFile("{$this->baseUrl()}/public/externals/tinymce/tinymce.min.js");
?>

<script type="text/javascript">
tinymce.init({
    selector: "textarea.span5",
    theme: "modern",
    //width: 300,
    //height: 300,
    plugins: [
         "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
         "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
         "save table contextmenu directionality emoticons template paste textcolor"
   ],
   content_css: "css/content.css",
   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
   style_formats: [
        {title: 'Bold text', inline: 'b'},
        {title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
        {title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
        {title: 'Example 1', inline: 'span', classes: 'example1'},
        {title: 'Example 2', inline: 'span', classes: 'example2'},
        {title: 'Table styles'},
        {title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
    ]
 });
</script>

<?php
    $menu = array('menu' => 'admin_top_menu');
    echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<h4>
    <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
    <?php echo $this->translate('Admin Panel [Edit Mail]'); ?>
</h4>
    
<div style="clear: both;"><br /></div>
    
<div class="span add-company-form" style="margin-left: 0px;">
    <?php echo $this->form->render($this); ?>
</div>

<script type="text/javascript">
    $('#submit').prepend("<i class='icon-edit icon-white'></i> ");
</script>